const pickupLines = [
  "Are you a magician? Because whenever I look at you, everyone else disappears. 🎩✨",
  "Is your dad a boxer? Because you're a knockout! 👊💥",
  "Do you believe in love at first sight, or should I walk by again? 👀",
  "Is your name Google? Because you have everything I've been searching for. 😍",
  "Are you a camera? Because every time I look at you, I smile. 📸😊",
  "Do you have a Band-Aid? I just scraped my knee falling for you. 🩹😂",
  "Do you believe in fate? Because I think we were meant to meet. ⭐️🤗",
  "Is your name Wi-Fi? Because I'm really feeling a connection. 📶😉",
  "Are you an interior decorator? Because when I saw you, the entire room became beautiful. 🏠✨",
  "Is your dad an artist? Because you're a masterpiece. 🎨👌",
  "Is your dad a baker? Because you're a cutie pie! 🥧😘",
  "Can I follow you home? Cause my parents always told me to follow my dreams. 🏡✨",
  "Is your dad a thief? Because he must have stolen the stars and put them in your eyes. ✨😍",
  "Is your name Google? Because you're the answer to everything I'm searching for. 🔍💕",
  "If you were a fruit, you'd be a fineapple. 🍍😄",
  "Is your name Wi-Fi? Because I'm really feeling a connection. 📶😉",
  "Are you a magician? Because whenever I look at you, everyone else disappears. 🎩✨",
  "If you were a vegetable, you'd be a cute-cumber. 🥒😂",
  "Is your dad a boxer? Because damn, you're a knockout! 👊💥",
  "Is your name Wi-Fi? Because I'm really feeling a connection. 📶😉",
  "If you were a fruit, you'd be a fineapple. 🍍😄",
  "Is your dad a baker? Because you're a cutie pie! 🥧😘",
  "Do you have a Band-Aid? Because I just scraped my knee falling for you. 🩹😄",
  "Is your name Wi-Fi? Because I'm really feeling a connection. 📶😉",
  "Are you a parking ticket? Because you've got 'Fine' written all over you. 🎫😄",
  "Are you made of copper and tellurium? Because you're Cu-Te! 😄",
  "Do you believe in love at first sight or should I walk by again? 👀❤️",
  "Are you French? Because Eiffel for you. 🇫🇷😁",
  "Do you have a name or can I call you mine? 😄🙃",
  "Are you an interior decorator? Because when I saw you, the entire room became beautiful. 🏠✨",
  "Are you a Wi-Fi signal? Because I'm really feeling a connection. 📶😏",
  "Do you have a Band-Aid? Because I just scraped my knee falling for you. 🩹😄",
  "Is your dad a boxer? Because damn, you're a knockout! 👊💥",
  "Is your name Wi-Fi? Because I'm really feeling a connection. 📶😉",
  "If you were a fruit, you'd be a fineapple. 🍍😄",
  "Are you French? Because Eiffel for you. 🇫🇷😉",
  "Is your dad a baker? Because you're a cutie pie! 🥧😘",
  "Do you have a Band-Aid? Because I just scraped my knee falling for you. 🩹😄",
  "Is your name Wi-Fi? Because I'm really feeling a connection. 📶😉",
  "If you were a fruit, you'd be a fineapple. 🍍😄",
  "Do you have a name or can I call you mine? 😄🙃",
  "Is your dad a thief? Because he must have stolen the stars and put them in your eyes. ✨😍",
  "Do you believe in karma? Because I think we should do naughty things and let the universe balance it out. 😈⚖️",
  "Are you an alien? Because you just abducted my heart. 👽💘",
  "Is your dad a thief? Because you stole my heart. 💔😉",
  "Do you have a name, or can I call you mine? 😘💕",
  "Are you a magician? Because whenever I look at you, everyone else disappears. 🎩✨",
  "Do you believe in love at first sight, or should I walk by again? 👀❤️",
  "If you were a vegetable, you'd be a cute-cumber. 🥒😂",
  "Are you a Wi-Fi signal? Because I'm really feeling a connection. 📶😏",
  "Do you have a name or can I call you mine? 😄🙃",
  "Is your dad a boxer? Because damn, you're a knockout! 👊💥",
  "Excuse me, but I think you dropped something: my jaw. 😮💔",
];

module.exports = pickupLines;
